-- --------------------------------------------------------
-- ホスト:                          127.0.0.1
-- サーバーのバージョン:                   10.3.7-MariaDB - mariadb.org binary distribution
-- サーバー OS:                      Win64
-- HeidiSQL バージョン:               11.2.0.6213
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;


-- kampo のデータベース構造をダンプしています
DROP DATABASE IF EXISTS `kampo`;
CREATE DATABASE IF NOT EXISTS `kampo` /*!40100 DEFAULT CHARACTER SET utf8 */;
USE `kampo`;

--  テーブル kampo.relationship の構造をダンプしています
DROP TABLE IF EXISTS `relationship`;
CREATE TABLE IF NOT EXISTS `relationship` (
  `relation_id` int(11) NOT NULL,
  `relationship` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`relation_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- エクスポートするデータが選択されていません

--  テーブル kampo.relatives の構造をダンプしています
DROP TABLE IF EXISTS `relatives`;
CREATE TABLE IF NOT EXISTS `relatives` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `shoshin_id` int(11) DEFAULT NULL,
  `relationship` int(11) DEFAULT NULL,
  `status` int(11) DEFAULT NULL,
  `detail` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_shoshin_relatives` (`shoshin_id`),
  KEY `FK_relationship` (`relationship`),
  CONSTRAINT `FK_relationship` FOREIGN KEY (`relationship`) REFERENCES `relationship` (`relation_id`),
  CONSTRAINT `FK_shoshin_relatives` FOREIGN KEY (`shoshin_id`) REFERENCES `shoshin` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- エクスポートするデータが選択されていません

--  テーブル kampo.shoshin の構造をダンプしています
DROP TABLE IF EXISTS `shoshin`;
CREATE TABLE IF NOT EXISTS `shoshin` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` int(11) DEFAULT NULL,
  `age` int(11) DEFAULT NULL,
  `sex` int(11) DEFAULT NULL,
  `occupation` int(11) DEFAULT NULL,
  `height` int(11) DEFAULT NULL,
  `weight` int(11) DEFAULT NULL,
  `body_temp` int(11) DEFAULT NULL,
  `most_concern` int(11) DEFAULT NULL,
  `concern_detail` int(11) DEFAULT NULL,
  `other_hospital_diagnosis` int(11) DEFAULT NULL,
  `appetite` int(11) DEFAULT NULL,
  `sleep` int(11) DEFAULT NULL,
  `stool_frequency` int(11) DEFAULT NULL,
  `bowel_movement` int(11) DEFAULT NULL,
  `stool_property` int(11) DEFAULT NULL,
  `remaining_stool` int(11) DEFAULT NULL,
  `stomachache` int(11) DEFAULT NULL,
  `stomach_tension` int(11) DEFAULT NULL,
  `stomach_gas` int(11) DEFAULT NULL,
  `taking_laxative` int(11) DEFAULT NULL,
  `stomachahe_by_laxative` int(11) DEFAULT NULL,
  `urine_flequency` int(11) DEFAULT NULL,
  `urine_after_bed` int(11) DEFAULT NULL,
  `menstruation` int(11) DEFAULT NULL,
  `first_tite_age` int(11) DEFAULT NULL,
  `menopause_age` int(11) DEFAULT NULL,
  `last_menstruation_date` int(11) DEFAULT NULL,
  `last_menstruation_lasting` int(11) DEFAULT NULL,
  `menstruation_rhythm` int(11) DEFAULT NULL,
  `menstruation_length` int(11) DEFAULT NULL,
  `menstrual_pain` int(11) DEFAULT NULL,
  `menstruation_pain_killer` int(11) DEFAULT NULL,
  `menstruation_amount` int(11) DEFAULT NULL,
  `menstrual_upset` int(11) DEFAULT NULL,
  `abnormal_bleeding` int(11) DEFAULT NULL,
  `vaginal_discharge` int(11) DEFAULT NULL,
  `past_pregnancy` int(11) DEFAULT NULL,
  `past_birth` int(11) DEFAULT NULL,
  `spontaneous_miscarriage` int(11) DEFAULT NULL,
  `artificial_miscarriage` int(11) DEFAULT NULL,
  `constitution_atsugari` int(11) DEFAULT NULL,
  `constitution_samugari` int(11) DEFAULT NULL,
  `constitution_hie_zenshin` int(11) DEFAULT NULL,
  `constitution_hie_te` int(11) DEFAULT NULL,
  `constitution_hie_ashi` int(11) DEFAULT NULL,
  `constitution_hie_hara` int(11) DEFAULT NULL,
  `constitution_hie_koshi` int(11) DEFAULT NULL,
  `constitution_hie_se` int(11) DEFAULT NULL,
  `constitution_hie_other` int(11) DEFAULT NULL,
  `constitution_nobose` int(11) DEFAULT NULL,
  `constitution_hienobose` int(11) DEFAULT NULL,
  `constitution_tukare_zenshin` int(11) DEFAULT NULL,
  `constitution_tukare_ashi` int(11) DEFAULT NULL,
  `constitution_tukare_ude` int(11) DEFAULT NULL,
  `constitution_tukare_other` int(11) DEFAULT NULL,
  `constitution_omoi_zenshin` int(11) DEFAULT NULL,
  `constitution_omoi_koshi` int(11) DEFAULT NULL,
  `constitution_omoi_hiza` int(11) DEFAULT NULL,
  `constitution_omoi_ashi` int(11) DEFAULT NULL,
  `constitution_omoi_ude` int(11) DEFAULT NULL,
  `constitution_omoi_other` int(11) DEFAULT NULL,
  `constitution_darui_zenshin` int(11) DEFAULT NULL,
  `constitution_darui_ashi` int(11) DEFAULT NULL,
  `constitution_darui_ude` int(11) DEFAULT NULL,
  `constitution_darui_other` int(11) DEFAULT NULL,
  `constitution_chikara_zenshin` int(11) DEFAULT NULL,
  `constitution_chiakra_koshi` int(11) DEFAULT NULL,
  `constitution_chikara_hiza` int(11) DEFAULT NULL,
  `constitution_chikara_ashi` int(11) DEFAULT NULL,
  `constitution_chikara_ude` int(11) DEFAULT NULL,
  `constitution_chikara_other` int(11) DEFAULT NULL,
  `constitution_ase_zenshin` int(11) DEFAULT NULL,
  `constitution_ase_atama` int(11) DEFAULT NULL,
  `constitution_ase_tenohira` int(11) DEFAULT NULL,
  `constitution_ase_ashiura` int(11) DEFAULT NULL,
  `constitution_ase_other` int(11) DEFAULT NULL,
  `constitution_asegadenai` int(11) DEFAULT NULL,
  `constitution_nease` int(11) DEFAULT NULL,
  `constitution_okan` int(11) DEFAULT NULL,
  `constitution_akufu` int(11) DEFAULT NULL,
  `constitution_hatsunetsu` int(11) DEFAULT NULL,
  `constitution_binetsu` int(11) DEFAULT NULL,
  `constitution_netsukan` int(11) DEFAULT NULL,
  `constitution_nemuke` int(11) DEFAULT NULL,
  `constitution_kaze` int(11) DEFAULT NULL,
  `constitution_himan` int(11) DEFAULT NULL,
  `constitution_yase` int(11) DEFAULT NULL,
  `constitution_taijuzoka` int(11) DEFAULT NULL,
  `constitution_taijugensho` int(11) DEFAULT NULL,
  `constitution_kashoku` int(11) DEFAULT NULL,
  `constitution_kyoshoku` int(11) DEFAULT NULL,
  `constitution_suibun` int(11) DEFAULT NULL,
  `constitution_mukumi` int(11) DEFAULT NULL,
  `constitution_lymph` int(11) DEFAULT NULL,
  `constitution_lymph_hare` int(11) DEFAULT NULL,
  `constitution_raynoud` int(11) DEFAULT NULL,
  `constitution_kayumi` int(11) DEFAULT NULL,
  `constitution_kanso` int(11) unsigned zerofill DEFAULT NULL,
  `constitution_fukaikan` int(11) DEFAULT NULL,
  `constitution_oudan` int(11) DEFAULT NULL,
  `constitution_kusuguttagari` int(11) DEFAULT NULL,
  `constitution_fuankan` int(11) DEFAULT NULL,
  `constitution_shousoukan` int(11) DEFAULT NULL,
  `constitution_mukiryoku` int(11) DEFAULT NULL,
  `constitution_yuutsu` int(11) DEFAULT NULL,
  `constitution_asatsurai` int(11) DEFAULT NULL,
  `constitution_iraira` int(11) DEFAULT NULL,
  `constitution_okorippoi` int(11) DEFAULT NULL,
  `constitution_kibunshogai` int(11) DEFAULT NULL,
  `constitution_yonaki` int(11) DEFAULT NULL,
  `constitution_hagishiri` int(11) DEFAULT NULL,
  `constitution_shinkeikabin` int(11) DEFAULT NULL,
  `constitution_wasureppoi` int(11) DEFAULT NULL,
  `constitution_ishikishogai` int(11) DEFAULT NULL,
  `constitution_shisshin` int(11) DEFAULT NULL,
  `constitution_chiho` int(11) DEFAULT NULL,
  `constitution_genkaku` int(11) DEFAULT NULL,
  `constitution_gencho` int(11) DEFAULT NULL,
  `constitution_nioi` int(11) DEFAULT NULL,
  `constitution_zutsu_zukizuki` int(11) DEFAULT NULL,
  `constitution_zutsu_kirikiri` int(11) DEFAULT NULL,
  `constitution_zutsu_shimetsuke` int(11) DEFAULT NULL,
  `constitution_zutsu_other` int(11) DEFAULT NULL,
  `constitution_zuju` int(11) DEFAULT NULL,
  `constitution_memai_kaiten` int(11) DEFAULT NULL,
  `constitution_memai_hikaiten` int(11) DEFAULT NULL,
  `constitution_furatsuki` int(11) DEFAULT NULL,
  `constitution_tachikurami` int(11) DEFAULT NULL,
  `constitution_kurumayoi` int(11) DEFAULT NULL,
  `constitution_hakkan` int(11) DEFAULT NULL,
  `constitution_hotflash` int(11) DEFAULT NULL,
  `constitution_chikaku` int(11) DEFAULT NULL,
  `constitution_mahi` int(11) DEFAULT NULL,
  `constitution_chikakuijo` int(11) DEFAULT NULL,
  `constitution_furue` int(11) DEFAULT NULL,
  `constitution_hikitsuri` int(11) DEFAULT NULL,
  `constitution_keiren` int(11) DEFAULT NULL,
  `constitution_undoumahi` int(11) DEFAULT NULL,
  `constitution_ganmenmahi` int(11) DEFAULT NULL,
  `constitution_hokoukonnan` int(11) DEFAULT NULL,
  `constitution_ashimotsure` int(11) DEFAULT NULL,
  `constitution_ashiagarinikui` int(11) DEFAULT NULL,
  `constitution_tsumazuki` int(11) DEFAULT NULL,
  `constitution_taijouhoushin` int(11) DEFAULT NULL,
  `constitution_mune_appakukan` int(11) DEFAULT NULL,
  `constitution_mune_tsumari` int(11) DEFAULT NULL,
  `constitution_mune_shimetsuke` int(11) DEFAULT NULL,
  `constitution_mune_moyamoya` int(11) DEFAULT NULL,
  `constitution_mune_other` int(11) DEFAULT NULL,
  `constitution_muneitai` int(11) DEFAULT NULL,
  `constitution_fuseimyaku` int(11) DEFAULT NULL,
  `constitution_hinmyaku` int(11) DEFAULT NULL,
  `constitution_jomyaku` int(11) DEFAULT NULL,
  `constitution_douki` int(11) DEFAULT NULL,
  `constitution_joumyakuryu` int(11) DEFAULT NULL,
  `constitution_seki_karazeki` int(11) DEFAULT NULL,
  `constitution_seki_tan` int(11) DEFAULT NULL,
  `constitution_tan_mizu` int(11) DEFAULT NULL,
  `constitution_tan_nebari` int(11) DEFAULT NULL,
  `constitution_tan_umi` int(11) DEFAULT NULL,
  `constitution_kokyu_ansei` int(11) DEFAULT NULL,
  `constitution_kokyu_undou` int(11) DEFAULT NULL,
  `constitution_kettan` int(11) DEFAULT NULL,
  `constitution_kakketsu` int(11) DEFAULT NULL,
  `constitution_ikigire` int(11) DEFAULT NULL,
  `constitution_kizakokyu` int(11) DEFAULT NULL,
  `constitution_zyanose` int(11) DEFAULT NULL,
  `constitution_shokugonemuke` int(11) DEFAULT NULL,
  `constitution_tabesugiichou` int(11) DEFAULT NULL,
  `constitution_sugugeri` int(11) DEFAULT NULL,
  `constitution_suguharu` int(11) DEFAULT NULL,
  `constitution_outo` int(11) DEFAULT NULL,
  `constitution_toketu` int(11) DEFAULT NULL,
  `constitution_donki` int(11) DEFAULT NULL,
  `constitution_geppu` int(11) DEFAULT NULL,
  `constitution_muneyake` int(11) DEFAULT NULL,
  `constitution_isan` int(11) DEFAULT NULL,
  `constitution_imotare` int(11) DEFAULT NULL,
  `constitution_inofukaikan` int(11) DEFAULT NULL,
  `constitution_munetsukae` int(11) DEFAULT NULL,
  `constitution_fukutsuue` int(11) DEFAULT NULL,
  `constitution_fukutsushita` int(11) DEFAULT NULL,
  `constitution_fukutsuido` int(11) DEFAULT NULL,
  `constitution_kirokubu` int(11) DEFAULT NULL,
  `constitution_kirokubukurushi` int(11) DEFAULT NULL,
  `constitution_haragorogoro` int(11) DEFAULT NULL,
  `constitution_houhi` int(11) DEFAULT NULL,
  `constitution_benihinkai` int(11) DEFAULT NULL,
  `constitution_ketsuben` int(11) DEFAULT NULL,
  `constitution_geketsu` int(11) DEFAULT NULL,
  `constitution_ji` int(11) DEFAULT NULL,
  `constitution_dakko` int(11) DEFAULT NULL,
  `constitution_koumontsu` int(11) DEFAULT NULL,
  `constitution_gantsu` int(11) DEFAULT NULL,
  `constitution_shiryokuteika` int(11) DEFAULT NULL,
  `constitution_menotsukare` int(11) DEFAULT NULL,
  `constitution_menokasumi` int(11) DEFAULT NULL,
  `constitution_menojuketsu` int(11) DEFAULT NULL,
  `constitution_menokayumi` int(11) DEFAULT NULL,
  `constitution_menokanso` int(11) DEFAULT NULL,
  `constitution_mabushi` int(11) DEFAULT NULL,
  `constitution_menogorogoro` int(11) DEFAULT NULL,
  `constitution_menohirihiri` int(11) DEFAULT NULL,
  `constitution_meyani` int(11) DEFAULT NULL,
  `constitution_gankenkasui` int(11) DEFAULT NULL,
  `constitution_fukushi` int(11) DEFAULT NULL,
  `constitution_shiyakyosaku` int(11) DEFAULT NULL,
  `constitution_miminari` int(11) DEFAULT NULL,
  `constitution_atamanari` int(11) DEFAULT NULL,
  `constitution_jiheikan` int(11) DEFAULT NULL,
  `constitution_nancho` int(11) DEFAULT NULL,
  `constitution_mimidare` int(11) DEFAULT NULL,
  `constitution_kushami` int(11) DEFAULT NULL,
  `constitution_hanajiru_mizu` int(11) DEFAULT NULL,
  `constitution_hanajiru_nebari` int(11) DEFAULT NULL,
  `constitution_hanajiru_umi` int(11) DEFAULT NULL,
  `constitution_hanazumari` int(11) DEFAULT NULL,
  `constitution_hanagaomoi` int(11) DEFAULT NULL,
  `constitution_kobiro` int(11) DEFAULT NULL,
  `constitution_hanashukketsu` int(11) DEFAULT NULL,
  `constitution_ibiki` int(11) DEFAULT NULL,
  `constitution_nioiwakarazu` int(11) DEFAULT NULL,
  `constitution_ajishinai` int(11) DEFAULT NULL,
  `constitution_ajiokashi` int(11) DEFAULT NULL,
  `constitution_kuchivirukawaku` int(11) DEFAULT NULL,
  `constitution_kokatsu` int(11) DEFAULT NULL,
  `constitution_kokan` int(11) DEFAULT NULL,
  `constitution_kuchinigami` int(11) DEFAULT NULL,
  `constitution_konaien` int(11) DEFAULT NULL,
  `constitution_shitashimiru` int(11) DEFAULT NULL,
  `constitution_koshu` int(11) DEFAULT NULL,
  `constitution_zettsu` int(11) DEFAULT NULL,
  `constitution_shitsu` int(11) DEFAULT NULL,
  `constitution_haguki` int(11) DEFAULT NULL,
  `constitution_engekonnan` int(11) DEFAULT NULL,
  `constitution_nodoitami` int(11) DEFAULT NULL,
  `constitution_nodookukanso` int(11) DEFAULT NULL,
  `constitution_nodotsumari` int(11) DEFAULT NULL,
  `constitution_nodoigaiga` int(11) DEFAULT NULL,
  `constitution_shakkuri` int(11) DEFAULT NULL,
  `constitution_koekasure` int(11) DEFAULT NULL,
  `constitution_hosshin` int(11) DEFAULT NULL,
  `constitution_nikibi` int(11) DEFAULT NULL,
  `constitution_atopy` int(11) DEFAULT NULL,
  `constitution_jinmashin` int(11) DEFAULT NULL,
  `constitution_shimoyake` int(11) DEFAULT NULL,
  `constitution_hadaare` int(11) DEFAULT NULL,
  `constitution_hifukanso` int(11) DEFAULT NULL,
  `constitution_hifukayumi` int(11) DEFAULT NULL,
  `constitution_hifuabura` int(11) DEFAULT NULL,
  `constitution_shikisochinchaku` int(11) DEFAULT NULL,
  `constitution_dasshoku` int(11) DEFAULT NULL,
  `constitution_menokuma` int(11) DEFAULT NULL,
  `constitution_azadekiyasui` int(11) DEFAULT NULL,
  `constitution_hikashukketsu` int(11) DEFAULT NULL,
  `constitution_daisen` int(11) DEFAULT NULL,
  `constitution_datsumo_enkei` int(11) DEFAULT NULL,
  `constitution_datsumo_zenpan` int(11) DEFAULT NULL,
  `constitution_kegakoi` int(11) DEFAULT NULL,
  `constitution_shiraga` int(11) DEFAULT NULL,
  `constitution_fuke` int(11) DEFAULT NULL,
  `constitution_ibo` int(11) DEFAULT NULL,
  `constitution_tsumemoroi` int(11) DEFAULT NULL,
  `constitution_tsumeijo` int(11) DEFAULT NULL,
  `constitution_shujutuato` int(11) DEFAULT NULL,
  `constitution_hifukano` int(11) DEFAULT NULL,
  `constitution_keroid` int(11) DEFAULT NULL,
  `constitution_itami_koshi` int(11) DEFAULT NULL,
  `constitution_itami_kata` int(11) DEFAULT NULL,
  `constitution_itami_se` int(11) DEFAULT NULL,
  `constitution_itami_hiza` int(11) DEFAULT NULL,
  `constitution_itami_ude` int(11) DEFAULT NULL,
  `constitution_itami_shushi` int(11) DEFAULT NULL,
  `constitution_itami_futomomo` int(11) DEFAULT NULL,
  `constitution_itami_ashi` int(11) DEFAULT NULL,
  `constitution_itami_other` int(11) DEFAULT NULL,
  `constitution_kowabari_shushi` int(11) DEFAULT NULL,
  `constitution_kori_kata` int(11) DEFAULT NULL,
  `constitution_kori_se` int(11) DEFAULT NULL,
  `constitution_kori_sesuji` int(11) DEFAULT NULL,
  `constitution_kori_koshi` int(11) DEFAULT NULL,
  `constitution_kori_other` int(11) DEFAULT NULL,
  `constitution_hari` int(11) DEFAULT NULL,
  `constitution_hare_hiza` int(11) DEFAULT NULL,
  `constitution_hare_hiji` int(11) DEFAULT NULL,
  `constitution_hare_tekubi` int(11) DEFAULT NULL,
  `constitution_hare_other` int(11) DEFAULT NULL,
  `constitution_shibire_ude` int(11) DEFAULT NULL,
  `constitution_shibire_tekubi` int(11) DEFAULT NULL,
  `constitution_shibire_futomomo` int(11) DEFAULT NULL,
  `constitution_shibire_ashi` int(11) DEFAULT NULL,
  `constitution_shibire_other` int(11) DEFAULT NULL,
  `constitution_hoteri_tenohira` int(11) DEFAULT NULL,
  `constitution_hoteri_ashinoura` int(11) DEFAULT NULL,
  `constitution_hoteri_other` int(11) DEFAULT NULL,
  `constitution_shinkeitsu` int(11) DEFAULT NULL,
  `constitution_ashitsuru` int(11) DEFAULT NULL,
  `constitution_kinryokuteika` int(11) DEFAULT NULL,
  `constitution_kanketsusei` int(11) DEFAULT NULL,
  `constitution_undoushogai` int(11) DEFAULT NULL,
  `constitution_daboku` int(11) DEFAULT NULL,
  `constitution_funin` int(11) DEFAULT NULL,
  `constitution_taiiijou` int(11) DEFAULT NULL,
  `constitution_shikyudatsu` int(11) DEFAULT NULL,
  `constitution_seikoutsu` int(11) DEFAULT NULL,
  `constitution_chibusahari` int(11) DEFAULT NULL,
  `constitution_obishitakessei` int(11) DEFAULT NULL,
  `constitution_obishitanousei` int(11) DEFAULT NULL,
  `constitution_obishitaother` int(11) DEFAULT NULL,
  `constitution_hinnyo` int(11) DEFAULT NULL,
  `constitution_yakanhinnyo` int(11) DEFAULT NULL,
  `constitution_nyoshikkin` int(11) DEFAULT NULL,
  `constitution_yanyosho` int(11) DEFAULT NULL,
  `constitution_nyonigori` int(11) DEFAULT NULL,
  `constitution_nyoryogensho` int(11) DEFAULT NULL,
  `constitution_nyosukunai` int(11) DEFAULT NULL,
  `constitution_nyohei` int(11) DEFAULT NULL,
  `constitution_seikinougentai` int(11) DEFAULT NULL,
  `constitution_einbufukai` int(11) DEFAULT NULL,
  `constitution_einbutsu` int(11) DEFAULT NULL,
  `constitution_kougantsu` int(11) DEFAULT NULL,
  `constitution_other` int(11) DEFAULT NULL,
  `drink_startage` int(11) DEFAULT NULL,
  `drink_stopage` int(11) DEFAULT NULL,
  `drink_past` int(11) DEFAULT NULL,
  `drink_past_amount` int(11) DEFAULT NULL,
  `drink_current` int(11) DEFAULT NULL,
  `drink_current_amount` int(11) DEFAULT NULL,
  `smoke_startage` int(11) DEFAULT NULL,
  `smoke_stopage` int(11) DEFAULT NULL,
  `smoke_past` int(11) DEFAULT NULL,
  `smoke_past_amount` int(11) DEFAULT NULL,
  `smoke_current` int(11) DEFAULT NULL,
  `smoke_current_amount` int(11) DEFAULT NULL,
  `preference` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- エクスポートするデータが選択されていません

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
